apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    env: demo
spec:
  replicas: 3
  selector:
    env: demo
    type: frontend
  template:
    metadata:
      name: nginx-pod-demo
      labels:
        env: demo
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "512m"
            requests:
              memory: "64Mi"
              cpu: "256m"
          ports:
            - containerPort: 80
