apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
    - image: redis:alpine
      name: redis-container
      ports:
        - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
